# Generated by Django 2.2.1 on 2019-05-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='summary',
            new_name='body',
        ),
        migrations.AddField(
            model_name='article',
            name='create_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
